version: '3.3'

services:
    http:
        image: nginx
        expose:
            - '80'
        environment:
            VIRTUAL_HOST: kvalue.localhost
        volumes:
            - ./docker/http/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/html:cached
        networks:
            - default
            - reverse-proxy

    php:
        build:
            context: ./docker/php
        volumes:
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
            - ./:/var/www/html:cached

    db:
        image: postgres:13
        environment:
            - POSTGRES_USER=kvalue
            - POSTGRES_PASSWORD=kvalue
        volumes:
            - kvalue_db_data:/var/lib/postgresql/data:cached
        ports:
            - "5435:5432"

volumes:
    kvalue_db_data: { }

networks:
    reverse-proxy:
        external: true
